port = 8081
pollingMs = 100
sqsMinimumMessageSize = 1
#sqsMaximumMessageSize = 1048576 #TODO
sqsMaximumMessageSize = 1048
routePattern = "/message"
mode = "release"
compression = "none"
sqsQueueName = "mytestqueue2"
separatingCharacters = "|%"
